### ISSUE TITLE
config_motionnet.yml file missing

### ISSUE THREAD

**Issue by dexception** [TheToadAlly/MotionBlur#15]
FileNotFoundError: [Errno 2] No such file or directory: 'motion_blur/libs/configs/config_motionnet.yml'

**Comment by luczeng** [comment]
Sorry for the late reply, I haven't had much time to work on this project.

You can use motion_blur/libs/configs/config_reds.yml

You can also use the branch feature/lz_resnet_backbone which has the latest improvements. I wont be able to merge it in the next few weeks at the very least.
